server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:toolkey.p12
    key-alias: ${simpletools.ssl.key-alias}
    key-store-password: ${simpletools.ssl.key-store-password}
    key-store-type: ${simpletools.ssl.key-store-type}
spring:
  application:
    name: simple_tools
  profiles:
    active: test
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${simpletools.mysql.host}:${simpletools.mysql.port}/${simpletools.mysql.db}
      username: ${simpletools.mysql.username}
      password: ${simpletools.mysql.password}

jwt:
  secret: ${simpletools.jwt.secret}

wx:
  mp:
    appId: ${simpletools.wx.appId}
    secret: ${simpletools.wx.secret}
    token: ${simpletools.wx.token}
    aesKey: ${simpletools.wx.aesKey}
    callback: ${simpletools.wx.callback}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
