spring:
  application:
    name: simple_tools
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${simpletools.mysql.host}:${simpletools.mysql.port}/${simpletools.mysql.db}
      username: ${simpletools.mysql.username}
      password: ${simpletools.mysql.password}
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
